### ISSUE TITLE
RFC - Move view switching based on content type to Controller

### ISSUE THREAD

**Issue by markstory** [cakephp/cakephp#16113]
### Description

Historically `RequestHandlerComponent` has handled the various responsibilities related to content-type negotiation in CakePHP. However, as we continue to embrace middleware and fix some of the problematic behavior  in `RequestHandlerComponent` it is hard challenging to fix those problems and maintain backwards compatibility. Because of these challenges request body decoding is being split into a middleware (#16099) and this issue is a proposal for the view switching functionality RequestHandler provides.

## Why in the Controller?

We cannot easily choose the view class from middleware which leaves us with implementing that logic as a controller or component feature. While adding a new component would work, I think we can have an easier to operate and more flexible API by using controller methods.

## Proposed methods/properties

To move the decision of what view to use to the controller we need a new way to define the view classes a controller wants to negotiate between, some logic to do the content negotiation, and a way to set the view class.

## Choosing the views for a controller

A controller can define the views it supports using a `protected $viewClasses = string[]` or by defining the `getViewClasses(): array` method. The property version allows users with simple requirements to use a declarative interface, while more custom logic can be implemented in the method. The default implementation of `getViewClasses()` would return the value of `$viewClasses`

```php
class ArticlesController extends AppController
{
    protected $viewClasses = [JsonView::class, AjaxView::class, View::class];
}
```

The default value of `viewClasses` would be `View::class` as to not enable content negotiation for existing applications.

In order for a list of view classes to be able to negotiate types with the request, View classes can implement a method describing the content type they respond with.

```php
public static function getContentType(): string
{
    return 'text/html';
}
```

This method would default to `text/html` to ensure existing view classes aren't used for custom types. Another potential solution to connecting content types and view classes is to define a mapping in the controller between the extension/content type and view class:

```php
// An alternate solution to content type mappings
protected $viewClasses = ['xml' => XmlView::class, 'json' => JsonView::class, '*' => View::class];
```

This implementation has some drawbacks which make me prefer the previous solution. The content type a view handles is not defined by the View class, which isn't great for encapsulation. Instead documentation needs to be read, and mappings need to be duplicated in each controller that needs customization. This creates more opportunity for errors, and makes for a poorer developer experience.

### Content type negotiation

Once the list of potential view classes is known the controller can use the request's `Accept` header or `_ext` parameter to perform content-negotiation. If a request has `_ext` set that extension will be mapped back to its content-type and that content type will be used to do content-negotiation. Otherwise the `Accept` header will be used.

To compare the current request's `Accept` header and the controller's view class content types, we would need to extract the content negotiation logic from RequestHandler into a utility class that provides the following interface:

```php
interface ContentTypeNegotiation
{
    /**
     * Using the `Accept` header of the provided request, choose
     * one of the $types provided.
     *
     * @param $request The request to get content type preferences [[from]]
     * @param $types The possible valid choices.
     * @return string The preferred $type value.
     */
    public function prefers(RequestInterface $request, string[] $types): string
    {
    }
}
```
:warning: This interface was not implemented. If you need to customize the negotiation strategy you can override controller methods.

This would allow us to extract the existing logic from `RequestHandler` and reuse it in the component and new controller behavior. The negotiation logic would be put into the `chooseViewClass(ServerRequest $request): string` so that user-land code can replace the process if required. This method would be called from `Controller::beforeRender()` but only if the ViewBuilder doesn't already have a view class assigned. This allows listeners to the `beforeRender` event to see the view class selection and change it if required, and defers the logic to decide content types until it is required so that redirects don't incur overhead.
 
### Todo

- [x] Get ContentTypeNegotiation created.
- [x] Add getContentType to View classes.
- [x] Add controller methods
- [ ] Update ExceptionRenderer::_getController()

### CakePHP Version

4.4.0

**Comment by othercorey** [comment]
> The property version allows users with simple requirements to use a declarative interface, while more custom logic can be implemented in the method.

Is this a convention we want to adopt or just require implementing the method? Double documentation can be confusing.

**Comment by markstory** [comment]
> Is this a convention we want to adopt or just require implementing the method? Double documentation can be confusing.

That is a good point about doubling the documentation and the 'right' way to do things. Perhaps the property should be scrapped and only the method should be used.

**Comment by markstory** [comment]
Going to close this as everything outlined here has been implemented.
