### ISSUE TITLE
Better transactions support

### ISSUE THREAD

**Issue by lorenzo** [cakephp/cakephp#9500]
This is a meta ticket to track progress on improving transaction handling:
- [ ] Transactions should automatically rollback on any `Throwable` (refs #8997)
- [ ] We should have an easy way to change the transaction isolation level (refs #3136)
- [ ] Add a `onConflict` to the Query API. This method will abstract the specifics of each driver for handling constraint problems when updating or inserting (refs #7458). This will open the door for having a `upsert` method in tables.

**Comment by thinkingmedia** [comment]
Transactions should be separated from the DB connection so that a transaction handler can be configured by the user. This would allow users to install their own transaction handling policy such as "retrying" transactions that trigger a deadlock SQL error.

In the current ORM there is no way to implement the above. In order to retry transactions I had to use my own wrapper function that caught the deadlock error, and then repeat execution of a callback to recreate the transaction.

When running multiple clients against a shared DB a deadlock in MySQL is very common problem, and the standard (even documented solution) is to retry the transaction. Sadly, MySQL does not do this automatically, but just running the transaction again is enough to recover from the error.

**Comment by inoas** [comment]
It should also be easy to setup through `app.php` which Transaction Mode / Handler to pick by default.
