### ISSUE TITLE
Database Types improvements

### ISSUE THREAD

**Issue by lorenzo** [cakephp/cakephp#9502]
This ticket tracks improvements that should be done to the typing system in the database layer:
- [x] Allow ValueBinder to bind many values in a batch. (refs #8426)
- [x] Improve type casting performance by batching cast calls. This means that Type classes can implement methods to cast many arguments in a function call.
- [x] Allow disabling type casting in results. This could be done by offering a separate `ResultSet` class. (refs #7137)
- [x] Add a complete space-efficient implementation of a UUID type. This will help us have a reference implementation for complex Types (refs #7013)
- [ ] Add a `CastExpression` and automatically cast function expressions when the type is known. This will require making sure all our expression classes have a `returnType` like `FunctionExpression` does (refs #7534)

**Comment by markstory** [comment]
Sounds great, would these be targetting 3.4?

**Comment by lorenzo** [comment]
@markstory These were my personal goals for 3.4, let's see if I can have them all done before a beta :)

**Comment by markstory** [comment]
Sounds like a plan to me :+1:

**Comment by Oxicode** [comment]
+1

**Comment by dereuromark** [comment]
I would like to see

- [ ] (JsonType)[https://github.com/dereuromark/cakephp-shim/blob/master/src/Database/Type/JsonType.php] respect nullable (default not null / default null) field schema definition. See [tests](https://github.com/dereuromark/cakephp-shim/blob/master/tests/TestCase/Database/Type/JsonTypeTest.php#L100) for details.

**Comment by dereuromark** [comment]
This list above seems to be almost ticket off, anything we want to include in 4.x now?

**Comment by markstory** [comment]
Automatic casting of function results would be nice to have. But it can be done in 4.1 without breaking compatibility.

**Comment by othercorey** [comment]
Moved CastExpression to roadmap.
